#!/usr/bin/env node

import fs from 'fs/promises';
import process from 'process';

const conventionalCommitMessageRegExp = /^(BREAKING CHANGE|build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\w ])+([\s\S]*)/g;

const commitMsgFile = process.argv[2];
const message = await fs.readFile(commitMsgFile, 'utf8');
const isValid = conventionalCommitMessageRegExp.test(message);

if (!isValid) {
  console.log('Cannot commit: the commit message does not comply with conventional commits standards.');
  process.exit(1);
}
